server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    hikari:
      username: root
      password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  signer_key: "Er29N6vTLTvgEtLjQwimrY9unr6Zec5A5nxu32nIRghZYXl4ZFhgtbysCWuh9rDw"


